# on push to main branch build and create new release with zipped dist folder
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: zip -r dist.zip dist package.json package-lock.json
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip

# create new tag with git short_sha and upload dist.zip as release asset
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Get git short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist.zip